"""Map of city codes to city names for Total Energies API.

This map is used to map API city codes to actual city names.
Fill in the mappings as needed.
"""

# Map: city_code (int or str) -> city_name (str)
CITY_CODE_TO_NAME = {
    # Example format:
    # 1: "ADANA",
    # 2: "ADIYAMAN",
    # Add your mappings here...
    1: "ADANA",
    2: "ADIYAMAN",
    3: "AFYONKARAHİSAR",
    4: "AĞRI",
    5: "AKSARAY",
    6: "AMASYA",
    7: "ANKARA",
    8: "ANTALYA",
    84: "ARDAHAN",
    66: "ARTVİN",
    9: "AYDIN",
    10: "BALIKESİR",
    11: "BARTIN",
    12: "BATMAN",
    81: "BAYBURT",
    13: "BİLECİK",
    14: "BOLU",
    15: "BURDUR",
    16: "BURSA",
    67: "BİNGÖL",
    68: "BİTLİS",
    18: "ÇANKIRI",
    19: "ÇORUM",
    20: "DENİZLİ",
    21: "DİYARBAKIR",
    22: "DÜZCE",
    23: "EDİRNE",
    69: "ELAZIĞ",
    24: "ERZİNCAN",
    25: "ERZURUM",
    26: "ESKİŞEHİR",
    27: "GAZİANTEP",
    28: "GİRESUN",
    70: "GÜMÜŞHANE",
    71: "HAKKARİ",
    29: "HATAY",
    31: "ISPARTA",
    32: "İSTANBUL",
    33: "İZMİR",
    30: "IĞDIR",
    34: "KAHRAMANMARAŞ",
    35: "KARABÜK",
    36: "KARAMAN",
    72: "KARS",
    37: "KASTAMONU",
    38: "KAYSERİ",
    39: "KIRIKKALE",
    40: "KIRKLARELİ",
    41: "KIRŞEHİR",
    42: "KOCAELİ",
    43: "KONYA",
    44: "KÜTAHYA",
    86: "KİLİS",
    45: "MALATYA",
    46: "MANİSA",
    73: "MARDİN",
    48: "MUGLA",
    74: "MUŞ",
    49: "NEVŞEHİR",
    50: "NİĞDE",
    51: "ORDU",
    52: "OSMANİYE",
    53: "RİZE",
    54: "SAKARYA",
    55: "SAMSUN",
    56: "SİVAS",
    57: "SİNOP",
    78: "SİİRT",
    59: "TEKIRDAG",
    60: "TOKAT",
    61: "TRABZON",
    79: "TUNCELİ",
    62: "UŞAK",
    80: "VAN",
    63: "YALOVA",
    64: "YOZGAT",
    65: "ZONGULDAK",
    17: "ÇANAKKALE",
    47: "MERSİN",
    58: "SANLIURFA",
    82: "ŞIRNAK",
}

